# Ch04 NumPy 數值計算 進階

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

## 隨機函數
- np.random.rand(dim0\[, dim1, dim2, ...\])
- np.random.randint(low, high=None, size=None)
- 參考資料: 
  - [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
  - [python numpy 常用随机数的产生方法](https://blog.csdn.net/m0_37804518/article/details/78490709)

In [4]:
'''
np.random.seed(42)
numpy.random.rand(): 設定種子後，取得隨機亂數

註: np.random.seed() 的引數固定，隨機產生的值也會固定，亂數的值介於 [0, 1)
'''
np.random.seed(23)
a = np.random.rand(3); a

array([0.51729788, 0.9469626 , 0.76545976])

In [5]:
'''
np.random.randint(start, end - 1, size=數量): 產生 start 到 end - 1 之間的整數值

隨機產生 100 位同學的成績
'''
a = np.random.randint(0, 100, size=(1,100), dtype='int32'); a

# np.array((2,4))


array([[31, 76, 91, 39, 90, 25, 51,  6, 45, 12, 49, 66, 75, 85, 69, 64,
        12, 21, 48, 41, 79, 90, 62, 57, 19, 33, 59, 39, 15, 36, 65,  1,
        43, 15, 86, 83, 58, 25, 66, 74, 35, 96, 56, 13, 60, 22, 38, 31,
        94, 78,  0, 21,  6, 32, 98, 32, 14, 31, 78, 83, 80, 70, 66, 82,
        85, 55, 27, 62, 43, 74, 71, 42, 83, 21,  6, 68, 22, 43,  8, 85,
        62, 32, 60, 11,  1, 41, 26, 37, 41, 56, 39, 81, 32, 53, 35, 23,
        29, 42, 38,  4]])

In [18]:
'''
np.random.shuffle(): 陣列元素重新排列
'''
x = np.arange(10)
np.random.shuffle(x)
x

array([9, 7, 4, 3, 2, 6, 8, 1, 5, 0])

## 統計運算

### 平均 mean()

In [20]:
# mean(): 元素平均值 - 1D
x = np.array([[1, 2, 3, 4]])
np.mean(x)

2.5

In [21]:
# mean(): 元素平均值 - 2D
x = np.array([[1, 2], [3, 4]])
np.mean(x)

2.5

In [22]:
# mean() 加上 axis
x = np.array([[1, 2], [3, 4]])
np.mean(x, axis = 0)

array([2., 3.])

### 中位數 median()

In [23]:
# median(): 中位數
x = np.array([[12, 7, 4], [3, 2, 6]])
np.median(x)

5.0

In [24]:
# median() 加上 axis
np.median(x, axis = 0)

array([7.5, 4.5, 5. ])

### 變異數 var()

In [27]:
# var(): 變異數 (variance) (離散隨機變數) (一維陣列)
'''
import math
mean = (1 + 2 + 3 + 4) / 4
(math.pow(1 - mean, 2) + math.pow(2 - mean, 2) + math.pow(3 - mean, 2) + math.pow(4 - mean, 2)) / 4

補充: var() 也可以設定 axis
'''
x = np.array([1, 2, 3, 4])
np.var(x)

1.25

In [31]:
# var(): 變異數 (variance) (離散隨機變數) (二維陣列)
'''
import math

x_ = x.ravel()
mean_X = np.mean(x_)
sum = 0

for i in x_:
    sum += math.pow(i-mean_X, 2)

sum / len(x_)
'''

x = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])
np.var(x)



4.6875

### 標準差 var()

In [35]:
# std(): 標準差 (standard deviation) - 1D array
'''
變異數 = 「標準差」的平方
標準差 = 「變異數」開根號
'''

x = np.array([1, 2, 3, 4])
np.std(x)

1.118033988749895

In [39]:
# std(): 標準差 (standard deviation) - 2D array
x = np.array([[1, 2, 3, 4], [2, 4, 6, 8]])
np.std(x)

2.165063509461097

In [40]:
# std() 加上 axis
np.std(x, axis=0)

array([0.5, 1. , 1.5, 2. ])

### 累計加總 cumsum()

In [43]:
# 1D Array
x = np.arange(10)

np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [54]:
# 2D Array
x = np.arange(10).reshape(2,-1); x

# np.cumsum(x)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
np.cumsum(x, axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35]])

In [56]:
np.cumsum(x, axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13]])

## 邏輯運算

### any()

In [57]:
# 一個滿足就返回 True
ar=np.array([9, 9, 4, 7])
np.any((ar%7)==0)

True

### all()

In [59]:
# 全部為真才返回 True
ar=np.array([9, 9, 4, 7])
np.all((ar%7)==0)

False

In [60]:
ar=np.array([7, 14, 28, 35])
np.all((ar%7)==0)

True

## 廣播 Broadcasting

執行 2 個陣列運算時，原則上必須外形相同才能運算，如果不同，可以使用廣播 (broadcasting) 機制，將小陣列「擴大」到兩個陣列都相同，之後再進行運算。

![Computation on Arrays: Broadcasting](https://i.imgur.com/CuB6Bsh.png)
參考資料: [Computation on Arrays: Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [62]:
ar=np.ones((3,2)); ar

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
ar2=np.array([2,3]); ar2

array([2, 3])

In [64]:
# 缺失維度自動補滿
ar + ar2

array([[3., 4.],
       [3., 4.],
       [3., 4.]])

### Broadcasting works across dimensions

In [74]:
ar=np.array([[23,24,25]]); ar

array([[23, 24, 25]])

In [75]:
ar.T

array([[23],
       [24],
       [25]])

In [76]:
ar.T+ar

array([[46, 47, 48],
       [47, 48, 49],
       [48, 49, 50]])