# Ch02 NumPy basic operation 

In [3]:
import numpy as np

In [4]:
# 版本確認
np.__version__

'1.23.5'

## 陣列索引與切片 (Indexing & Slicing)

### 1D array

In [5]:
x = np.array([-3, 4, 6, 9, 8, 3]); x

array([-3,  4,  6,  9,  8,  3])

In [6]:
# 指定索引
x[0]

-3

In [7]:
# 切片 (範圍: [start, end-1, step])
x[0:2]

array([-3,  4])

In [8]:
# 切片，指定每幾步算一次
'''
這樣也可以
x[::2]
'''
x[0:5:2]

array([-3,  6,  8])

In [9]:
# 切片 (使用負號)
x[-1]

3

In [10]:
# 切片 (範圍: [start, end-1, step])
x[-3:-1]

array([9, 8])

### 2D array

In [11]:
x2 = np.array([[2,3,4],[9,8,7],[11,12,13]]); x2

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [12]:
x2[1,1]

8

In [13]:
# Retrieve row 2
x2[2]


array([11, 12, 13])

In [14]:
x2[2, :]

array([11, 12, 13])

In [15]:
# Retrieve column 1
x2[:,1]

array([ 3,  8, 12])

In [16]:
x2[1:,::2]

array([[ 9,  7],
       [11, 13]])

## 塑型 reshape

In [17]:
x2

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [18]:
# reshape
x2.reshape(9,1)

array([[ 2],
       [ 3],
       [ 4],
       [ 9],
       [ 8],
       [ 7],
       [11],
       [12],
       [13]])

In [19]:
# reshape
x2.reshape(1,9)

array([[ 2,  3,  4,  9,  8,  7, 11, 12, 13]])

### Fancy indexing

In [20]:
np.random.seed(42)
x = np.random.randint(100 , size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [21]:
# access three different elements
# 取三個元素 組成一個list
[x[3], x[7], x[2]]

[71, 86, 14]

In [22]:
# fancy index
# 陣列中 放陣列格式
x[[3,7,2]]

array([71, 86, 14])

### 效能測試

In [23]:
%timeit x2[1,2]

98.7 ns ± 2.42 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [24]:
%timeit x2[1][2]

196 ns ± 3.26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [25]:
# summary for vector
vec = np.array([-3, 4, 6, 9, 8, 3])
print("vec - 4th value:", vec[3])

vec[3] = 19
print("vec - 4th value (changed):", vec[3])

# summary for matrix
mat = np.array([
    [2, 4, 6, 8],
    [10, 12, 14, 16]
])
print("mat - 1st row:", mat[0])
print("mat - 2nd row's 1st value:", mat[1, 0])
print("mat - last row's last value:", mat[-1, -1])

vec - 4th value: 9
vec - 4th value (changed): 19
mat - 1st row: [2 4 6 8]
mat - 2nd row's 1st value: 10
mat - last row's last value: 16


## 陣列的遮罩

In [26]:
np.random.seed(10)
ar=np.random.randint(0,25,10); ar

array([ 9,  4, 15,  0, 17, 16, 17,  8,  9,  0])

In [27]:
evenMask=(ar%2==0); evenMask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
evenNums=ar[evenMask]; evenNums

array([ 4,  0, 16,  8,  0])

## 陣列的串接

In [29]:
# 陣列結合
'''
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
'''

x = np.array([1,2,3])
y = np.array([11,22,33])

z = np.concatenate((x, y)); z


array([ 1,  2,  3, 11, 22, 33])

In [30]:
# 將陣列元素加入其它陣列
z = np.concatenate((x, [12, 14, 16])); z

array([ 1,  2,  3, 12, 14, 16])

### Vertical Stacking 

In [41]:

# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertical stack them
np.vstack((arr1, arr2))




array([[1, 2],
       [3, 4],
       [5, 6]])

### Horizontal Stacking

In [43]:
# Create two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Horizontal stack them
np.hstack((arr1, arr2))



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 陣列的複製 np.copy()

In [31]:
arr = np.arange(8); arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
arr_copy = arr.copy(); arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
# check memory id

print("arr 記憶體位址: ", id(arr))
print("arr_copy 記憶體位址: ", id(arr_copy))

arr 記憶體位址:  2175057060816
arr_copy 記憶體位址:  2175057058608


In [34]:
arr_copy[0] = -1

print("before copy: ", arr)
print("after copy: ", arr_copy)


before copy:  [0 1 2 3 4 5 6 7]
after copy:  [-1  1  2  3  4  5  6  7]


## 陣列指定索引插入元素 insert()

In [35]:
# 在陣列指定索引 2 插入元素 9
'''
numpy.insert(arr, obj, values, axis=None)
'''
x = np.array([2,4,6,8,10])

z = np.insert(x, 2, 9); z

array([ 2,  4,  9,  6,  8, 10])

In [36]:
# 在陣列指定索引 1 跟 3，分別插入元素 7 跟 9
x = np.array([2,4,6,8,10])

z = np.insert(x, [1,3], [7,9]); z

array([ 2,  7,  4,  6,  9,  8, 10])

## 刪除指定索引的陣列元素 delete()

In [37]:
# 刪除索引 1 的元素
'''
numpy.delete(arr, obj, axis=None)
'''
x = np.array([2,4,6,8,10])

z = np.delete(x, 1); z

array([ 2,  6,  8, 10])

In [38]:
# 刪除索引 1 和 3 所放置的元素
x = np.array([2,4,6,8,10])

z = np.delete(x, [1, 3]); z

array([ 2,  6, 10])