# Ch01 Create NumPy Array

In [1]:
import numpy as np

## NumPy 陣列創建 via numpy.array
NumPy arrays can be created via the numpy.array constructor directly

In [2]:
# 語法查詢
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [4]:
# 在未完成的語法後面按下 tab 鍵，會開啟自動完成功能 (語法提示) 
np.ar

AttributeError: module 'numpy' has no attribute 'ar'

## NumPy array vs Python list performance

In [1]:
import time
import numpy as np

size_of_vec = 1000000

def python_list():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1

def numpy_array():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


count1 = python_list()
count2 = numpy_array()
print("****** Test run with {} elements ******".format(size_of_vec))
print("Python list: {}".format(count1))
print("NumPy array: {}".format(count2))
print("NumPy array is " + str(count1/count2) + " faster!")

****** Test run with 1000000 elements ******
Python list: 0.6522014141082764
NumPy array: 0.00798344612121582
NumPy array is 81.69422129311631 faster!


In [3]:
# 資料類型確認
arr = np.array([3, 5, 7, 9])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
# 如果希望宣告變數後，直接預覽變數，可以用「;」隔開，寫在同一行:
a = np.array([3, 5, 7, 9]); a

array([3, 5, 7, 9])

#### np.arange(): 從數值範圍來建立陣列

In [5]:
# 跟 range() 用法一樣
'''
用法:
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
'''
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# 取得陣列 [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.arange(1, 10); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# 1 ~ 10 之間，每隔 3 個元素，加入資料到陣列: [1, 4, 7]
a = np.arange(1, 10, 3); a

array([1, 4, 7])

#### np.linspace(): 從數值範圍透過線性切割建立陣列

In [12]:
# 線性分割
'''
用法:
args - start element,end element, number of elements
'''
a = np.linspace(0, 10, 4); a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## NumPy 資料型態

In [13]:
# 自動判斷資料型態
a = np.array([1,2,3,4]); a.dtype

dtype('int32')

In [15]:
# 自動判斷資料型態 (其中一個元素變成浮點數，dtype 會自動轉型)
a = np.array([1.3, 2, 3, 4]); a.dtype

dtype('float64')

In [18]:
# 指定陣列每一個資料的資料型態 (指定 float 預設為 float64)
a = np.array([1, 2, 3, 4], dtype='float'); a.dtype
# arr8.dtype

dtype('float64')

In [25]:
# Unicode 最多9個字
arr =np.array(['Goodbye','Welcome','Tata','Goodnight']); arr.dtype

dtype('<U9')

In [26]:
# 最多9個字元
arr[2] = "this is a book"
arr[2]

'this is a'

In [28]:
# numpy 有boolean資料型態 適用於masking

a = np.array([True, False, True, False]); a.dtype

dtype('bool')

In [46]:
# 傳回一個全新的整數陣列
a_float = np.array([1, 2, 3, 4], dtype='float'); a_float.dtype

a_int = a_float.astype(int); a_int.dtype


print("a_float: ", a_float)
print(f"a_float 記憶體位址: {id(a_float)}")

print("a_int: ", a_int)
print(f"a_int 記憶體位址: {id(a_int)}")


a_float:  [1. 2. 3. 4.]
a_float 記憶體位址: 1938922019920
a_int:  [1 2 3 4]
a_int 記憶體位址: 1938922018480


## Numpy 陣列的屬性
- shape, ndim, dtype, itemsize, size
### Dimensions or Axes in NumPy
- Scalars (0D Arrays)
- Vectors (1D Arrays)
- Matrices (2D Arrays)
- Tensor (3D Arrays)


In [47]:
# Scalars (0D Arrays)
s = np.array(21)

print(s)
print("Number of axes:", s.ndim)
print("data type:", s.dtype)
print("data size:", s.size)
print("Shape:", s.shape)

21
Number of axes: 0
data type: int32
data size: 1
Shape: ()


In [48]:
# Vectors (1D Arrays) 向量（一維陣列）
vec = np.array([-1, 2, 7, 9, 2])

print(vec)
print("Number of axes:", vec.ndim)
print("data type:", vec.dtype)
print("data size:", vec.size)
print("Shape:", vec.shape)

[-1  2  7  9  2]
Number of axes: 1
data type: int32
data size: 5
Shape: (5,)


In [49]:
# Matrices (2D Arrays) 矩陣（二維陣列）
mat = np.array([
    [1.2, 2.3, 3.3],
    [5.5, 6.3, 7.5]
])

print(mat)
print("Number of axes:", mat.ndim)
print("data type:", mat.dtype)
print("data size:", mat.size)
print("Shape:", mat.shape)

[[1.2 2.3 3.3]
 [5.5 6.3 7.5]]
Number of axes: 2
data type: float64
data size: 6
Shape: (2, 3)


In [50]:
# 3D Arrays 3D 陣列
t = np.array([
    [[1, 3, 9],
     [7, -6, 2]],

    [[2, 3, 5],
     [0, -2, -2]],

    [[9, 6, 2],
     [-7, -3, -12]],

    [[2, 4, 5],
     [-1, 9, 8]]
])

print(t)
print("Number of axes:", t.ndim)
print("data type:", t.dtype)
print("data size:", t.size)
print("Shape:", t.shape)

[[[  1   3   9]
  [  7  -6   2]]

 [[  2   3   5]
  [  0  -2  -2]]

 [[  9   6   2]
  [ -7  -3 -12]]

 [[  2   4   5]
  [ -1   9   8]]]
Number of axes: 3
data type: int32
data size: 24
Shape: (4, 2, 3)


## NumPy 陣列創建函式
These functions include 
- numpy.zeros, 
- numpy.ones, 
- numpy.eye, 
- nrandom.rand,
- numpy.random.randn,
- numpy.empty

#### numpy.zeros

In [51]:
# Produce 4x2 array of zeros.
# 配置記憶體空間，並將記憶體內容清0
arr_zeros =np.zeros((4,2)); arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

#### numpy.ones

In [54]:
# Produces 2x3x2 array of 1's.
# pandas 只支援二維資料結構
# 在深度學習tensor資料型態才會是三維資料結構
arr_ones =np.ones((2,3,4)); arr_ones

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### numpy.eye

In [55]:
# Produces identity matrix
arr_eye = np.eye(3); arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### numpy.empty

In [56]:
# np.empty(): 建立尚未初始化的陣列，裡面的元素是隨機產生的結果，換句話說，只產生陣列，值都是隨機產生的
# 註: 若需要初始化 (同時給元素預設的值)，建議使用 np.zeros、np.ones 或 np.fill
'''
numpy.empty(shape, dtype=float, order='C', *, like=None)
'''
arr_empty = np.empty((3,3)); arr_empty

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### numpy.full

In [58]:
# np.full(): 建立填滿 fill_value 的陣列，透過 shape 指定幾維 
'''
numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
'''
arr_full = np.full((3,4), 10); arr_full

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

### numpy.random.rand

In [60]:
# Using the rand, randn functions
# rand(m) produces an array of the given shape 
# with uniformly distributed random numbers over [0,1)
np.random.seed(200) # Set seed
arr_random = np.random.rand(10); arr_random

array([0.94763226, 0.22654742, 0.59442014, 0.42830868, 0.76414069,
       0.00286059, 0.35742368, 0.90969489, 0.45608099, 0.98180271])

In [62]:
# randn(m) produces m normally distributed (Gaussian) random numbers
arr_random_num = np.random.randn(3); arr_random_num

array([ 1.01734895,  1.91171178, -0.52967163])